name: Terraform Apply
on:
  push:

  workflow_dispatch:


jobs:
  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v2

      - name: Setup AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1


      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate 

      - name: Terraform Plan
        run: |
          cd terraform/
          terraform plan -out tfplan

      - name: Terraform Apply
        run: |
          cd terraform/
          terraform apply tfplan
       
  