name: Terraform Plan & Apply
on:
  push:

  workflow_dispatch:


jobs:
  terraform_apply:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v2

      - name: Setup AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: ap-south-1


      - name: Terraform Init, Plan & Apply
        run: |
          cd terraform/
          terraform init
          terraform plan -out tfplan 
          terraform apply tfplan